# Using official Node.js image with version >= 18
FROM node:18

# Setting the working directory inside the container
WORKDIR /app

# Copying package.json
COPY ./backend/package*.json ./

# Installing dependencies
RUN npm install

# Copying the rest of the application files
COPY ./backend .

# Expose the port that the Node.js app will run on
EXPOSE 8000

# Start the application using npm start
CMD ["npm", "start"]