apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortify-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: url.shortify.site 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shortify-backend-service  
            port:
              number: 8000          
